apiVersion: kustomize.reinoud.dev/v1
kind: GoogleSecretManagerSecretGenerator
metadata:
  name: generated
  annotations:
    config.kubernetes.io/function: |
      container:
        image: ghcr.io/reinoudk/krm-google-secret-manager:v0.1.0-local
spec:
  name: example
  project:
  secrets:
    - key: example-key
      source: example-source
