apiVersion: kustomize.reinoud.dev/v1
kind: GoogleSecretManagerSecretGenerator
metadata:
  name: generated
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ../../build/krm-google-secret-manager
spec:
  name: example
  project:
  secrets:
    - key: example-key
      source: projects/<your-project>/secrets/<your-secret>/versions/latest
